### ISSUE TITLE
Does iplant support globus？

### ISSUE THREAD

**Issue by wenbinmei** [cyverse/django-cyverse-auth#4]
Hi,

Does iplant support globus? Did not see on the iplant website, but found a python scripts support globus protocol ? Thanks.

-Wenbin

**Comment by deardooley** [comment]
You have support to gridftp, gsi openssh, myproxy, etc via the CyVerse Science APIs (Agave). If you need to use their transfer app or their identity provider, there no no current support for that in CyVerse. XSEDE would be your best bet.

—
Rion

**Comment by steve-gregory** [comment]
Hello @wenbinmei,

This repository helps connect similar authentication backends and login procedures between two Django services. In our case, [Atmosphere](github.com/iPlantCollaborativeOpenSource/atmosphere) and [Troposphere](github.com/iPlantCollaborativeOpenSource/troposphere)

While we do support Globus, WSO2, CAS, LDAP and SAML (at some level or another), this is not an indication that those protocols are globally supported across iPlant.

Currently, we are not using Globus OAuth for iPlant. 

This library is made public to help others who use Atmosphere as a service to authenticate their instances via globus..

Thanks for your interest.
-Steve Gregory
